# Generated by Django 5.1.4 on 2025-02-01 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradexapp', '0002_user_delete_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='loginid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tradexapp.login'),
            preserve_default=False,
        ),
    ]
