# Generated by Django 5.1.4 on 2025-02-01 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradexapp', '0004_userr_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userr',
            name='loginid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tradexapp.login'),
            preserve_default=False,
        ),
    ]
