# Generated by Django 5.1.4 on 2025-02-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradexapp', '0005_userr_loginid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userr',
            old_name='contact',
            new_name='Contact',
        ),
        migrations.RemoveField(
            model_name='userr',
            name='name',
        ),
        migrations.AddField(
            model_name='userr',
            name='Name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
