# Generated by Django 5.1.4 on 2025-02-02 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradexapp', '0007_login_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='Password',
            new_name='password',
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=20)),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradexapp.login')),
            ],
        ),
        migrations.DeleteModel(
            name='userr',
        ),
    ]
