# Generated by Django 5.1.4 on 2025-02-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradexapp', '0008_rename_email_login_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.CharField(max_length=100)),
                ('cdate', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
