# Generated by Django 5.1.4 on 2025-02-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradexapp', '0009_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMarketNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('source', models.CharField(max_length=255)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
