# Generated by Django 5.1.4 on 2025-02-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradexapp', '0010_stockmarketnews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='cdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
