# Generated by Django 5.1.4 on 2025-02-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradexapp', '0013_remove_customuser_status_customuser_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
